#!/bin/sh

set -e
set -x

SCRIPT=$(readlink -f "$0")
WORKSPACESFOLDER=$(dirname "$SCRIPT")/../../..

DOCKER_FILE=dockerfiles/cross-build/workspace

(cd $WORKSPACESFOLDER; balena build --deviceType raspberrypi3 --arch armv7 --dockerfile $DOCKER_FILE --logs)
