version: "2"
services:
    main:
        build: .
        restart: always
        network_mode: host
        privileged: true
        environment:
            - ROS_HOSTNAME=192.168.1.248
            - ROS_MASTER_URI=http://192.168.1.248:11311
            - BALENA_HOST_CONFIG_iomem=relaxed
            - BALENA_HOST_CONFIG_strict_devmem=0
        devices:
            - "/dev/mem:/dev/mem"
        cap_add:
            - SYS_RAWIO
        ports:
            - "11311:11311"
