version: "2"
services:
    main:
        build: .
        restart: always
        network_mode: host
        privileged: true
        devices:
            - "/dev/mem:/dev/mem"
        cap_add:
            - SYS_RAWIO
        labels:
            io.balena.features.kernel-modules: '1'
            io.balena.features.firmware: '1'
            io.balena.features.dbus: '1'
            io.balena.features.supervisor-api: '1'
            io.balena.features.balena-api: '1'
            io.balena.update.strategy: download-then-kill
            io.balena.update.handover-timeout: '60000'
