#!/bin/sh

set -e
set -x

SCRIPT=$(readlink -f "$0")
WORKSPACESFOLDER=$(dirname "$SCRIPT")/../../..

(cd $WORKSPACESFOLDER; balena build --deviceType raspberrypi3 --arch armv7 --dockerfile dockerfiles/cross-build/ros --logs)
