#!/bin/sh

# script/build: Build the workspace

set -e
set -x

SCRIPT=$(readlink -f "$0")
WORKSPACESFOLDER=$(dirname "$SCRIPT")/..
(cd $WORKSPACESFOLDER; catkin_make)
chmod +x $WORKSPACESFOLDER/devel/setup.sh
set +x
. $WORKSPACESFOLDER/devel/setup.sh
