#!/bin/sh

# script/build: Build the workspace

set -e
set -x

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path to the current workspace
WORKSPACEFOLDER=$(dirname "$SCRIPT")/..
rm -rf $WORKSPACEFOLDER/build
rm -rf $WORKSPACEFOLDER/devel
rm -rf $WORKSPACEFOLDER/install
