#!/bin/sh

set -e
set -x

SCRIPT=$(readlink -f "$0")
WORKSPACESFOLDER=$(dirname "$SCRIPT")/../..

(cd $WORKSPACESFOLDER; \
 rm -f docker-compose.yml Dockerfile; \
 set +x; \
 . $WORKSPACESFOLDER/external/devel/setup.sh; \
 set -x; \
 catkin_make; \
 chmod +x devel/setup.sh)

set +x

echo "Don't forget to run  \". devel/setup.sh\""
