#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
        echo 'This script must be run by root' >&2
        exit 1
fi

set -e
set -x

SCRIPT=$(readlink -f "$0")
WORKSPACESFOLDER=$(dirname "$SCRIPT")/../..

(cd $WORKSPACESFOLDER/external; rm -f docker-compose.yml Dockerfile; \
    . /opt/ros/melodic/setup.sh; catkin_make; \
    chmod +x devel/setup.sh )
